### ISSUE TITLE
add getMetricsTopConsumers

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#1039]
Lists top consumers of the api over a date range

[{
		"count": 7076,
		"consumer_id": "123123",
		"app_name": "Sofi"
	},
	{
		"count": 7020,
		"consumer_id": "12312312",
		"app_name": "Api Explorer"
	}
]

add filter by partial function  and implemented in version

**Comment by hongwei1** [comment]
`3c298f1` and `6145baf` , add the developer_email in response body
