### ISSUE TITLE
Portal : Landing page | Test your app using customer data uses wrong link 

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#105]
Should use the function exampleSandboxCredentialsLink in WebUI.scala to display the link

**Comment by sebtesobe** [comment]
Oops, @ichaib and i were discussing how to deal with sandbox-specific customer logins last week and we came up with the scheme as found in function `sandboxCredentialsLink` . We thought about not using an extra property.
But I  was not aware that these credentials are already found on sandbox-specific wiki pages (and seemingly also Ismail). If we stick to this mechanism, please delete `sandboxCredentialsLink` and also the wiki page https://github.com/OpenBankProject/OBP-API/wiki/Sandbox-credentials

**Comment by simonredfern** [comment]
Yep, There was no need to create an extra page or link. @ichaib please undo any new mechanism just introduced. Currently, if we deploy develop to existing sandboxes we will break the links to existing sandbox specific github pages - and thus deveopers won't be able to find test credentials and other specific information. Its a good idea to put more stuff in the landing page / portal but we'll probably still need a slimmed down specific page on github for quick changes (e.g. the elastic search info etc. etc.) At some point maybe we could have some more CMS functionality on the portal and could edit that instead of github.

**Comment by sebtesobe** [comment]
Since this seems urgent because of OP, i changed the code and removed the wiki page on github.
