### ISSUE TITLE
Create Customer does not return list of missing Roles if the role is missing

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#1132]
{
  "error": "OBP-20006: User is missing one or more roles: "
}

**Comment by simonredfern** [comment]
Also Resource Doc for this endpoint shows incorrect example response

**Comment by constantine2nd** [comment]
The first comment is already fixed at next commit: [Added test for endpoint createCustomer v3.0.0
](https://github.com/OpenBankProject/OBP-API/pull/1134/commits/df1714087ba26a7e5e480168049785ff1124d976)
