### ISSUE TITLE
Add new Resource: AccountApplication

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#1168]
Add new Resource: AccountApplication

POST /obp/v3.1.0/account-applicaitons

Body:
product_code String Required
user_id 		String Optional 
customer_id 	String Optional

Note:
user_id and/or customer_id must be present
user_id must be valid user_id
customer_id must be valid user_id

Body:

account_application_id UUID
product_code 
user {user object}
customer {customer object}
date_of_applicaiton Date
status String (REQUESTED)

GET /obp/v3.1.0/account-applicaitons

Body:
account-applicaitons List:

account_application_id
product_code 
user {user object}
customer {customer object}
date_of_applicaiton Date
status String (REQUESTED)

Requires Role CanGetAccountApplications 

GET /obp/v3.1.0/account-applicaitons/ACCOUNT_APPLICAITON_ID

Body:
account_application_id
product_code 
user {user object}
customer {customer object}
date_of_applicaiton Date
status String (REQUESTED)

PUT /obp/v3.1.0/account-applicaitons/ACCOUNT_APPLICAITON_ID/

Requires Role CanUpdateAccountApplications

Body:
status 

When status set to ACCEPTED we should create an Account 
type = AccountApplication.product_code
use getOrCreateAccountHolder to set the owner to the AccountApplication.user_id

**Comment by Jianwei-Tesobe** [comment]
Hi @simonredfern  
I have two questions as follow:
1. 
Note:
user_id` and/or` customer_id must be present
Do you mean this? both present is ok; only customer_id is present  also ok

2.
about: `status String (REQUESTED)`
Do you mean default value is a string value "REQUESTED" ?

**Comment by simonredfern** [comment]
1) Yes, if both user_id and customer_id are empty we should throw an error.
2) Yes, the string "REQUESTED"
