### ISSUE TITLE
Add a new resource: "Account Attribute"

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#1218]
Add a new resource: "Account Attribute"

{
"account_id":"asdfj68234769",  
"account_attribute_id":"asdfj68762834",  
"name":"OVERDRAFT_START_DATE",  
"type":"DATE_WITH_DAY",
"value":"2012-04-23"
}

Now, when an account is created, *create an account_attribute for each product attribute in the product*.

And add the following endpoints:

(requires Role CanGetAllAccountAttributes or owner View)
GET /obp/v3.1.0/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/account-attributes

(requires Role CanUpdateAllAccountAttributes)
PUT /obp/v3.1.0/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/account-attributes/ACCOUNT_ATTRIBUTE_ID

**Comment by constantine2nd** [comment]
Done.
