### ISSUE TITLE
Add transactionRequests_supported_types to Props file and related

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#123]
Add transactionRequests_supported_types to Props file.
This is a comma separated list of transaciton request types e.g. transactionRequests_supported_types=SANDBOX_TAN,INTRABANK

in the example props file we should have:
//transactionRequests_supported_types=SANDBOX_TAN,INTRABANK

and the default should be ""

Then,

1) 

in /OBP-API/src/main/scala/code/api/v2_0_0/APIMethods200.scala
lazy val createTransactionRequest where we have:

            isValidTransactionRequestType <- tryo(assert(transactionRequestType.value != "TRANSACTION_REQUEST_TYPE")) ?~! s"${ErrorMessages.InvalidTransactionRequestType} : Invalid value is: '${transactionRequestType.value}' Valid values are: ${TransactionRequests.CHALLENGE_SANDBOX_TAN}"

we should now check for those values from Props and return a matching list of valid values instead of just ${TransactionRequests.CHALLENGE_SANDBOX_TAN} 

And,

2)

In /OBP-API/src/main/scala/code/bankconnectors/LocalMappedConnector.scala  

  override def getTransactionRequestTypesImpl(fromAccount : BankAccount)

should use the list from transactionRequests_supported_types instead of hard coded string. (later this might be further filtered depending on what a user / account can do)

This will make v1.4.0 getTransactionRequestTypes to get the types from the Props file.

3)

Add a new call in v2.1.0

lazy val getTransactionRequestTypesSupportedByBank

GET

case "banks" :: BankId(bankId) :: "transaction-request-types"

This call will get all the transaction-request-types supported by the bank irrespective of Account/User/View

**Comment by somanole** [comment]
@simonredfern for the new call at 3) getTransactionRequestTypesSupportedByBank is user authentication required?

**Comment by somanole** [comment]
I suppose it's the same as getTransactionTypes - Authentication is Optional.

**Comment by simonredfern** [comment]
Can we close this ticket now?

**Comment by somanole** [comment]
Yes, we can close the ticket
