### ISSUE TITLE
For  add comment Empty box to Liftweb. error 

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-API#1230]
https://openlab-explorer.openbankproject.com/?version=3.1.0&list-all-banks=false&core=&psd2=&obwg=&ignoredefcat=true&bank_id=hsbc.01.hk.hsbc&account_id=27dcaa9f-16c3-41c1-b739-a998d9251cac&view_id=owner&counterparty_id=&transaction_id=#OBPv1_2_1-addCommentForViewOnTransaction

![image](https://user-images.githubusercontent.com/23308710/53128700-c1bf0080-3565-11e9-9606-e4909d0dd15b.png)

**Comment by constantine2nd** [comment]
@hongwei1 Ready for testing.
