### ISSUE TITLE
When superuser is needed, api should say so, not give unspecified or internal error 

### ISSUE THREAD

**Issue by chrisjsimpson** [OpenBankProject/OBP-API#1238]
**Scenario:** Administrator is adding the entitlement "CanCreateEntitlementAtAnyBank" to the current user which is *not* a super admin. They are confused with non-descript error message.  

**When** the api call to add the entitlement is sent : `curl -d '{"bank_id":"", "role_name":"CanCreateEntitlementAtAnyBank"}' -H "Content-Type: application/json" -H 'Authorization: DirectLogin token=""' -X POST http://localhost:8080//obp/v2.0.0/users/USER_ID/entitlements`

**Then** the error message should include a missing Super user account message.

**Current Scenario**

The api returns: `{"code":400,"message":"OBP-50005: An unspecified or internal error occurred."}` which doesn't give enough feedback to the caller.

Where the api response is currently defined: https://github.com/OpenBankProject/OBP-API/blob/721f454ff41c1b7e7b37249d5feebb039e412a05/src/main/scala/code/api/v2_0_0/APIMethods200.scala#L1964
Perhaps this message^ should be included in the error response.

**Comment by constantine2nd** [comment]
@chrisjsimpson Please take a look at next sanbox property: **display_internal_errors=true**.
Only in that case some message wouldn't be filtered.
Rules:
**display_internal_errors=true**  => Do not filter at all
**display_internal_errors=false**  => Show only messages which have the prefix **OBP-**

Solutions:
1. set the property display_internal_errors at the sandbox
2. Rename "Logged user is not super admin or does not have entitlements: " => "OBP-20101: Logged user is not super admin or does not have entitlements: "

**Comment by simonredfern** [comment]
2\. Rename "Logged user is not super admin or does not have entitlements: " => "OBP-20101: Current User is not super admin or is missing entitlements: "

**Comment by constantine2nd** [comment]
Resolved.
