### ISSUE TITLE
password recovery broken for  email address

### ISSUE THREAD

**Issue by tawoe** [OpenBankProject/OBP-API#1278]
I can trigger the password recovery by username, no problem. But if I want to reset by giving my email address, I get an error.

**Comment by tawoe** [comment]
on apisandbox

**Comment by tawoe** [comment]
same for newly created user

**Comment by constantine2nd** [comment]
An email address can be assigned to more than one username. It implies 2 cases:
1. one username <--> one email address
2.  more than one username <--> one email address

**Comment by tawoe** [comment]
one username <--> one email address => problem persists also in this case

**Comment by simonredfern** [comment]
Then - if an email address is entered email should be sent to that. 
If a username is entered email should be sent to all emails linked to that username.

**Comment by constantine2nd** [comment]
In case some person have two usernames linked to an email address how to know which one needs password recovery? Can we assume the both usernames need password recovery? @simonredfern

**Comment by constantine2nd** [comment]
@tawoe , @simonredfern 
For all cases we have next scenario:
1. Show message: **Thank you. If we found a matching user, password reset instructions have been sent.**
2. Redirect to home page.

Ready for testing.
