### ISSUE TITLE
How to setup db for test run of app?

### ISSUE THREAD

**Issue by spolnik** [OpenBankProject/OBP-API#13]
When I run tests I see that it's using ToSchemify to setup schema, which is fine. But in case of app run (test mode, as suggested on README) it's not setting up schema at all - as far as I've looked through wiki and notes there is no info on that topic.

Can you specify if there is automated way to set h2 schema for such run? Did I miss something?

Thanks,
Jacek

**Comment by kjyv** [comment]
Hey,
I'm not sure what you mean by app run (test mode). You can either start jetty and run the app or run single or all tests. There is no test mode and the Readme does not mention it.
In both cases, schemifyAll should be run as long as the corresponding props file has connector set to "mapped".

**Comment by spolnik** [comment]
Let me clarify, in the steps we have in README for 'To run with IntelliJ IDEA', when I follow them and run app I would expect that app will create in that way schema if it's not already there. Unfortunately what I have is empty h2 db (and yep, I have set connector to mapped).

It's very easy to reproduce, take totally fresh git develop branch, use test.default.props, run and try to register key or the user ;) It will say tables are not found, and as I've checked the db is not set actually.

**Comment by karensg** [comment]
Hi @spolnik,

I guess that you also have to add the configuration to the `.default.props` file. I think that `.test.default.props` is for running tests.
I followed all the steps in the Readme and my H2 database gets auto populated.

I hope it helps ;)

Karens

**Comment by spolnik** [comment]
that;s what I did - based on test.default.props.template I've created dev.default.props (without modifying anything) which doesn't work. Possibly it's kind of lift configuration detail I'm not aware about

**Comment by karensg** [comment]
`dev.default.props` does not work. When the mode is development you should use `.default.props`
See [https://www.assembla.com/wiki/show/liftweb/Properties](https://www.assembla.com/wiki/show/liftweb/Properties) for more info.

**Comment by kjyv** [comment]
Right, test.default.props will be used when running tests. Copy sample.props.template to e.g. default.props and make any necessary changes.

**Comment by spolnik** [comment]
thanks for info!
