### ISSUE TITLE
Make war Build version dynamically  

### ISSUE THREAD

**Issue by chrisjsimpson** [OpenBankProject/OBP-API#1300]
Currently the build system hardcodes the .war version number.

This needs to be dynamic because obviously the build breaks with it being hard-coded as new versions release.

@oldbig 
> can we set a param in jenkins config? such like:
`pom_version = mvn help:evaluate -Dexpression=project.version | grep -v ‘\[’`

**Comment by oldbig** [comment]
after check, it works follow these steps:

1. config POM_VERSION at "Pre Steps"
2. use POM_VERSION param at "Post Steps"
the attach files are screenshots:

<img width="935" alt="Shuang-screen 2019-06-04 pm11 05 10" src="https://user-images.githubusercontent.com/2577334/58891828-caf06980-871f-11e9-8cdd-44bc1cf4ea79.png">

<img width="1068" alt="Shuang-screen 2019-06-04 pm11 05 33" src="https://user-images.githubusercontent.com/2577334/58891840-cdeb5a00-871f-11e9-8640-7a907caf50fc.png">

define parameter:
`POM_VERSION=$(mvn help:evaluate -Dexpression=project.version | grep -v '\[')`

**Comment by chrisjsimpson** [comment]
:tada: thanks @oldbig that's brilliant. Let's add that too all builds asap. :+1:

**Comment by chrisjsimpson** [comment]
:+1: Develop branch is now updated to set war version dynamically. A build has been scheduled, will close this issue once tested.
