### ISSUE TITLE
CreateAccount returns 200 instead of 201 when an account is created

### ISSUE THREAD

**Issue by chrisjsimpson** [OpenBankProject/OBP-API#1314]
Regarding api call:  `/obp/v3.1.0/banks/BANK_ID/accounts/ACCOUNT_ID`

Steps to reproduce:

- Create a new account
- Observe the response code, it's `200`

Expected behaviour:

- Create a new account
- Observe the response code, should be `201` created

**Comment by constantine2nd** [comment]
@chrisjsimpson Ready for testing.
