### ISSUE TITLE
Update copyright year always to current year 

### ISSUE THREAD

**Issue by chrisjsimpson** [OpenBankProject/OBP-API#1392]
![image](https://user-images.githubusercontent.com/1718624/62693491-88226a80-b9ca-11e9-8d99-3a71f429f365.png)

Currently the copyright date is until 2018
Proposed solution: State the current year in the footer

**Comment by constantine2nd** [comment]
@chrisjsimpson Ready for testing.

**Comment by constantine2nd** [comment]
Resolved.
