### ISSUE TITLE
Payments URL unreachable

### ISSUE THREAD

**Issue by karensg** [OpenBankProject/OBP-API#14]
Hi,

I am trying to experiment with posting payments with the API 1.2.1 from the develop branch. However the application responds with:
```html
<!DOCTYPE html>
<html>
    <body>The Requested URL /obp/v1.2.1/banks/<bank_id>/accounts/b4a1609d-7b35-4730-a2c0-iuhih94f1b574/public/transactions was not found on this server</body>
</html> 
```
I have the same issue if I authenticate and use the `owner` view.
When I do a `GET` request, I do get all my transactions back.

I have `payments_enabled=true` and `allow_transactions_inserting=true` in my .props files.
The tests of API1_2_1Test also don't return any errors.

Did I forget to enable something or is this a bug?

Karens

**Comment by kjyv** [comment]
Is the response literally giving you the URL including <bank_id> or did you replace it for some reason? Of course that is a placeholder for an actual bank id you need to have in your database, same with the account id but that seems to look fine.

**Comment by karensg** [comment]
I replaced it with `<bank_id>`. The actual bank id I am experimenting with is available in the database. This is also the case with account id, as I am getting response from the `GET` request.

**Comment by kjyv** [comment]
I see. There may be situations where error handling needs to be improved so even if the url is existing but e.g. the json headers have an error you still get a 404. Did you have a look at the python payments example at https://github.com/OpenBankProject/Hello-OBP-OAuth1.0a-Python/blob/master/hello_payments.py ?

**Comment by karensg** [comment]
I already thought that there might be an error hiding somewhere. However the logs are not saying much.

I have properly implemented the nodeJS version: https://github.com/OpenBankProject/Hello-OBP-OAuth1.0a-Node. I can see the owner view of the account, so the oAuth part should work fine. I assume that the implementation is similar to Python?

**Comment by kjyv** [comment]
I'm not sure what you mean by properly implemented (set up?). However, the python version includes a sample for payments which the nodejs version does not have. If you can run the python sample fine it must be because of errors in the headers or a similar problem. If you get the same response, we need to look further.

**Comment by karensg** [comment]
All right, I will give Python a try

**Comment by karensg** [comment]
I tested it with the Python example and it worked. I found out what was the reason it was failing: I was missing a header `{'content-type': 'application/json'}`.

Thanks a lot for your suggestion to take a look at the Python example.
