### ISSUE TITLE
The spaces in username will break the DirectLogin

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-API#1415]
If there is space in username: 
eg: Hongwei Zhang.

Then, we can not get the directLogin token back!!!

![image](https://user-images.githubusercontent.com/23308710/64859738-5cc71700-d62b-11e9-842e-6b30ac0c79ab.png)

**Comment by constantine2nd** [comment]
Ready for testing.

**Comment by constantine2nd** [comment]
Resolved.
