### ISSUE TITLE
POST banks/BANK_ID/meetings → bad user ids

### ISSUE THREAD

**Issue by t0rst** [OpenBankProject/OBP-API#145]
When a new meeting record is created, the `meeting.present.staff_user_id` and `meeting.present.customer_user_id` fields are still being filled with the old style sequential user id instead of the newer style UUIDs, e.g.: `{"meeting_id":"aab0d370-376c-400e-be1b-6de68db1e04f", ... "present":{"staff_user_id":"0","customer_user_id":"44"}, ... }`

(Have workaround for now, so not blocking, but please fix.)

**Comment by simonredfern** [comment]
Assigned to Marko

**Comment by constantine2nd** [comment]
Ready for testing.
