### ISSUE TITLE
Option to run Mapped table access on a remote machine separated by Akka 

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#154]
Several banks have mentioned the need to put the database tables containing personal data into a different firewall zone.

Currently we have:

OBP-API -> Lift-web Mapper -> DB.

We will have 

OBP-API -> Akka -> Lift-web Mapper -> DB.

We should be able to reuse the "Lift-web Mapper" code.

Should work for the following models ResourceUser, View, ViewPermision, Counterparty

**Comment by simonredfern** [comment]
Linked to https://github.com/OpenBankProject/OBP-API/issues/187

**Comment by simonredfern** [comment]
Next to move to Akka:

    MappedCounterparty, //
    MappedCounterpartyMetadata, //
    MappedCounterpartyWhereTag, //
    AuthUser, //
    Nonce, //
    Token, //
    MappedTransactionRequest, //
    MappedMetric, //

**Comment by marko-md** [comment]
// The following tables will be accessed via Akka to the OBP Storage instance which in turn uses Mapper / JDBC:

- ViewImpl
- ViewPrivileges
- ResourceUser
- MappedComment
- MappedTag
- MappedWhereTag
- MappedTransactionImage
- MappedNarrative
- MappedCustomer
- MappedUserCustomerLink
- Consumer
- MappedCounterparty
- MappedCounterpartyMetadata
- MappedCounterpartyWhereTag
- MapperAccountHolders

  
Next to move to Akka:

- AuthUser
- Nonce
- Token
- MappedTransactionRequest
- MappedMetric

**Comment by simonredfern** [comment]
Please check we really need to move AuthUser in Kafka

**Comment by simonredfern** [comment]
Done except AuthUser see #551
