### ISSUE TITLE
Unnecessary account id's in kafka messages

### ISSUE THREAD

**Issue by ps7n** [OpenBankProject/OBP-API#167]
I'm working with OBP API, develop branch, Kafka integrated.

I'm calling the all accounts resource:
http://localhost:8080/obp/v2.1.0/banks/mybank/accounts

The north side inserts two requests in Kafka:
{"getBank":{"bankId":"mybank","username":"test@test.com"}}
{"getBankAccounts":{"bankIds":"mybank","username":"test@liferay.com","accountIds":"1"}}

The last one contains accountIds, which seems unnecessary as I'm retrieving all accounts.

Does OBP API store account information in OBP API local db?
Can we get rid of the accountIds attribute from getBankAccounts message?

I've discussed this issue with Simon Redfern via slack / emails.

**Comment by simonredfern** [comment]
@pbozin  : Is the confusion because there is one message to get all accounts and another to get specific accounts by id?

**Comment by pbozin** [comment]
getBankAccounts sends a list of accountIds, but gets that list from available views, if account doesn't have a view or it is restricted, it will not be included in the list
