### ISSUE TITLE
Get entitlements for another user returns SuperAdmin if logged in as SuperAdmin

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#171]
If you are logged in as a SuperAdmin and get the entitlements for any user, it always contains an entitlement with no id and role_name SuperAdmin. In this example, my user id is 'zyzop' and i query:

GET `/users/8417dd36-cfc8-4fa3-aac7-8d04ea42354f/entitlements`

```json
{
  "list":[{
    "entitlement_id":"",
    "role_name":"SuperAdmin",
    "bank_id":""
  }]
}
```

This example is from https://apisandbox.openbankproject.com/obp/v2.1.0

**Comment by marko-md** [comment]
@sebtesobe As is state in the code: if logged user is super admin then concatenate super user role to the list of assigned roles to user specified in the url, else return  the list of assigned roles to user specified in the url
@simonredfern , @sebtesobe As far as I can see in the code user does not have to be super admin to see a user roles. Is it wanted behaviour?

**Comment by simonredfern** [comment]
See https://github.com/OpenBankProject/OBP-API/issues/183

**Comment by sebtesobe** [comment]
I can't see this anymore, thanks!
