### ISSUE TITLE
Add API call to get all possible role names

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#173]
Currently, if you GET `/entitlements`, you get the granted roles, but sometimes it would be helpful to an API admin to know what roles are available, what could be granted. This could be sort of an export of the list in `src/main/scala/code/api/util/ApiRole.scala`

@simonredfern requested to assign the ticket to @marko-md .

**Comment by simonredfern** [comment]
Tweaked in ccc55d326ab5e9f407f97adba3e0240503d8351e
