### ISSUE TITLE
Make login screen responsive

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#18]

**Comment by sebtesobe** [comment]
Now that we have the login screen responsive, we should remove the kludge and integrate the responsiveness into all web pages, hoping it will go as smoothly as for the login page.

**Comment by everett-tesobe** [comment]
Sounds good.

On 18/04/2016 14:46, sebtesobe wrote:
> Now that we have the login screen responsive, we should remove the
> kludge and integrate the responsiveness into all web pages, hoping it
> will go as smoothly as for the login page.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenBankProject/OBP-API/issues/18#issuecomment-211365456>
> 

--

**Comment by simonredfern** [comment]
Now much better than before. (remaining issue is really about multiple logos on the header)
