### ISSUE TITLE
Sandbox: can't reach created account over api

### ISSUE THREAD

**Issue by misysdclabs** [OpenBankProject/OBP-API#181]
I created an account into the sandbox over https://sofisandbox.openbankproject.com.
I can see it on Sofi, but I can't find over the rest api. I can see only if I add a public view - but then everyone can see it. What did I do wrong?

@sebtesobe advised me to use OAuth and not DirectLogin for the authentication, and it should work, no matter if I call over api version 1.4.0 or 2.0.0.

So I took a look on the OAuth1.0a iOS project to see how to connect with OAuth (here: https://github.com/OpenBankProject/Hello-OBP-OAuth1.0a-IOS) And I just realised that I can't either reach my account from this iOS reference app, which is definitely using OAuth... I tried to login this app with a couple of example ones (like joe.bloggs@example.com, robert.uk.29@example.com, etc.), and for them it works perfectly...

Can anybody help me with this? I have these two usernames:
qspi
krisztian.kusper@misys.com

Thanks,
Krisztian

**Comment by sebtesobe** [comment]
Thanks for opening this ticket here. I can see 4 accounts linked to your 2 users. Let's focus on one account. Could you please provide me the account id (or set the account label using SoFi) you want to look at?

**Comment by misysdclabs** [comment]
please try to repeair this: qspi_erste_acc

**Comment by simonredfern** [comment]
Hi Krisztian. I've sent you a message on slack.
