### ISSUE TITLE
OAuth2 Sandboxes?

### ISSUE THREAD

**Issue by EricWilson-BluePrism** [OpenBankProject/OBP-API#1830]
Are there no OAuth2 sandboxes available? It seems the Beyond Banking sandbox is no longer active.

**Comment by simonredfern** [comment]
Hi Eric, Sorry for the delay. https://apiexplorersandbox.openbankproject.com/ is supporting OAuth2 . Please feel free to ask any questions here: https://chat.openbankproject.com/home
