### ISSUE TITLE
Simplify User model  

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#187]
Rename Models / Tables so their function is clearer / Are we sure we need two models?

**Comment by simonredfern** [comment]
Currently we have: 

API User which is the user that is used to validate accounts . API Users links to Views. (could rename to Resource User?)

OBP User which is ONLY username / password and email. It is used for login.
(could rename to Auth User or Login User)

We should rename: 
APIUser to ResourceUser 
and 
OBPUser to AuthUser

**Comment by marko-md** [comment]
@pbozin API User and OBP User have two fields which seems redundant.
OBP User:
- email
- username

OBP user
- email
- name_
Do we need it in both tables or we can remove they from one?

**Comment by simonredfern** [comment]
We now have AuthUser and ResourceUser
