### ISSUE TITLE
Email API Key when registering a new developer account

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/OBP-API#195]
As a developer who register for an API Key, I'd like to receive my account detail + API key via email so I can retrieve it anytime.

**Comment by simonredfern** [comment]
There should be a Props setting for this (true/false) with default false

**Comment by marko-md** [comment]
@simonredfern Ready for testing.

**Comment by marko-md** [comment]
Commits: 

- [Email API Key when registering a new developer account #195, first commit](https://github.com/OpenBankProject/OBP-API/commit/282b9e27038decda57ac659f802928b7e3e93bda)

- [Email API Key when registering a new developer account #195, tweaking property](https://github.com/OpenBankProject/OBP-API/commit/8acabed8f06bed119935a10ccab03ccf1c2cd114)
