### ISSUE TITLE
Management User wants to enable / disable api consumer keys (App keys) via API

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#197]
Add role CanGetConsumers
Add role CanDisableConsumers
Add role CanEnableConsumers

Add enabled [Boolean] to Consumer model (default False)

Add props setting: consumers_enabled_by_default = Boolean
When new consumers inserted they should use this setting.

Add endpoints: 

Require CanGetConsumers
GET /obp/v2.1.0/management/consumers/CONSUMER_ID
This should _only_ return fields listed in fieldsForList in OAuth.scala plus enabled field

Require CanEnableConsumers
PUT /obp/v2.1.0/management/consumers/CONSUMER_ID
{"enabled": "true"}

Require CanDisableConsumers
PUT /obp/v2.1.0/management/consumers/CONSUMER_ID
{"enabled": "false"}

Modify OAuth.scala and Direct Login so that only enabled Apps work.

**Comment by sebtesobe** [comment]
I reckon the GET call should not contain the CONSUMER_ID, just

GET /obp/v2.1.0/management/consumers/

Right?

**Comment by simonredfern** [comment]
I think its OK if the consumer_id is contained in the response even if its requested.

**Comment by simonredfern** [comment]
most of our responses work like that

**Comment by sebtesobe** [comment]
You mean that GET /obp/v2.1.0/management/consumers/ will return all consumers and GET /obp/v2.1.0/management/consumers/CONSUMER_ID will return one?

**Comment by simonredfern** [comment]
Yes

**Comment by simonredfern** [comment]
does that make sense?

**Comment by sebtesobe** [comment]
Yes

**Comment by marko-md** [comment]
@simonredfern Current message when api consumer is disabled is:
Bad response code (401) from OBP API server: {"error":"Invalid consumer credentials"}
Do we need to refine it, for instance "API consumer is disabled"?

**Comment by simonredfern** [comment]
Yes. I think that would be good.

**Comment by sebtesobe** [comment]
I deployed the current version of the API to https://apisandbox.openbankproject.com . I gave my user role `CanGetConsumers`. Now calling :
` /obp/v2.1.0/management/consumers` results in 404
` /obp/v2.1.0/management/consumers/` results in 500
` /obp/v2.1.0/management/consumers/<id>` results in 200 (good!)

How can you get a list of all consumers?

**Comment by marko-md** [comment]
@sebtesobe The endpoint has to be enhanced in order to get the list of all consumers

**Comment by sebtesobe** [comment]
@simonredfern Please make clear in issue description that an endpoint of some sort is required to get a list of all consumers

**Comment by marko-md** [comment]
@simonredfern endpoint GET /obp/v2.1.0/management/consumers will be added

**Comment by sebtesobe** [comment]
Looks like this is working, thanks @marko-md !

At some stage though, we need to implement some sort of pagination for the list, to get only x consumers at a time.
