### ISSUE TITLE
add navigation to API browser

### ISSUE THREAD

**Issue by znurgl** [OpenBankProject/OBP-API#20]
A layout like this would be really helpful: https://getmondo.co.uk/docs/

**Comment by simonredfern** [comment]
Good idea to have some kind of floating list / side panel of end points.

**Comment by simonredfern** [comment]
Creating a ticket on API Explorer for this

**Comment by simonredfern** [comment]
Here's the ticket on API Explorer https://github.com/OpenBankProject/API-Explorer/issues/1

**Comment by simonredfern** [comment]
This has been partially completed at least on API Explorer
