### ISSUE TITLE
Add functionality to limit calls per consumer key (App)

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#207]
We'll need several functions to set and check limits.

Need tests for the following functions:

/*
Sets the limit for calls by a consumer per the period
period can be one of HOURLY, DAILY, WEEKLY, MONTHLY, YEARLY

*/
def setConsumerLimit(consumerKey, period, value)

Store in the existing Consumer model (Model will need extending)

consumerKey is existing OAuth consumerKey

perMinuteCallLimit Double
perHourCallLimit Double
perDayCallLimit Double
perWeekCallLimit Double
perMonthCallLimit Double

/*

Get the limit for a consumer / period

*/

def getConsumerLimit(consumerKey, period) : Int

This will be used in admin interface for Consumer (from API Management)
 

/*
Checks if the consumer is within the various limits set

*/

def underConsumerLimits(consumerKey) : Boolean

This will be used by API to return error to client if False is returned.

/*

Increments consumerCounters

*/

def incrementConsumerCounters(consumerKey)

Should increment counters (yearly, monthly, weekly, daily) for consumer. Best to use something well suited to counter increments e.g. Redis.

keys should contain the value consumer_id + "perHour"

This will be called from all non public API endpoints. 

It will do nothing if Props use_consumer_limits = False

In Props we would add consumer_limits.redis_address, redis_port etc.

This function should reset counters at the periods. (all counters follow calendar)

Ref: PB2

Maybe look at https://stripe.com/blog/rate-limiters 

Maybe see if there are some existing rate limiting projects we can use 
https://github.com/sief/play-guard

https://gist.github.com/whysoserious/8581195 (but note there is no license so we can't use this at the moment)

**Comment by simonredfern** [comment]
If over rate limit, we should return response code as per:

http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#rate-limiting

**Comment by znurgl** [comment]
I start working on this.

**Comment by simonredfern** [comment]
Cool!

**Comment by simonredfern** [comment]
We should also have 

def incrementConsumerCounters(consumerKey, IPAddress)

so we can track IP addresses that are making a high number of calls.

**Comment by simonredfern** [comment]
hi @znurgl Any update ?

**Comment by simonredfern** [comment]
Done except AuthUser see #551
