### ISSUE TITLE
Modifications to v2.0.0 Add User Customer Link

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#212]
1) Add BANK_ID to the URL
/banks/user_customer_links
->
/banks/BANK_ID/user_customer_links

This makes the BANK_ID explicit instead of just relying on the bank in the customer.

2) Add CanCreateUserCustomerLink 
 case object CanCreateUserCustomerLink extends ApiRole{
    val requiresBankId = true
  }

3) Check User has CanCreateUserCustomerLink for BANK_ID specified in the URL

4) Check the Customer.bank specified by the CUSTOMER_ID matches BANK_ID

5) Use current date instead of sampleDate

6) Allow multiple User Customer Links for a user/bank. A user could represent several customers, one at each bank.

**Comment by marko-md** [comment]
@simonredfern the endpoint "/banks/BANK_ID/customers", Create Customer, also create and user to customer link after it create a customer. Do we need to guard it and omit creation if user  do not have CanCreateUserCustomerLink role for BANK_ID specified in the URL?

**Comment by simonredfern** [comment]
We should have two guards. (CanCreateUserCustomerLink and CanCreateCustomer)

**Comment by marko-md** [comment]
@simonredfern Ready for testing
