### ISSUE TITLE
Add resource and location header for POST KYC related resources

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#215]
v2.0.0 addKycStatus, addKycCheck, addKycDocument, addKycMedia should return the resource created (instead of {}) and put the location where we can GET the resource in the location header.

See https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html 10.2.2 201 Created

Also check that the id supplied is not used. 

Actually we should use PUT instead of POST because we are specifying the id - but the id should go in the URL not the body

**Comment by marko-md** [comment]
@simonredfern If we have endpoint "/customers/CUSTOMER_ID/kyc_documents" do we need an endpoint "/customers/CUSTOMER_ID/kyc_documents/KYC_DOCUMENT_ID"

**Comment by marko-md** [comment]
@simonredfern Ready for Testing
