### ISSUE TITLE
Add status flag to getTransactionRequestImpl 

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#224]
When answering a Transaction Request challenge, we should only retreive transaction requests that are INITIATED else we risk calling save transaction more than once.
Thus we need to only retreive INITIATED transaction requests.
Thus we need to adda flag here status: Option[Status]
If status is Empty return by id (whatever the status)
If status is Full also filter by the status  

def getTransactionRequestImpl(transactionRequestId: TransactionRequestId) : Box[TransactionRequest] = {
    // TODO need to pass a status variable so we can return say only INITIATED

**Comment by simonredfern** [comment]
Makes sense to work on this with #390

**Comment by hongwei1** [comment]
getTransactionRequestImpl is called two time in one "answering a Transaction Request challenge", it will be confused to check the Status in this level. Now all moved into API level.  #390
