### ISSUE TITLE
Direct Login with a third party authentication service

### ISSUE THREAD

**Issue by edenworky** [OpenBankProject/OBP-API#226]
This use case is not documented. Is it possible to get a Direct Login token (as documented [here](https://github.com/OpenBankProject/OBP-API/wiki/Direct-Login)) with a user authentication service (as documented [here](https://github.com/OpenBankProject/OBP-API/wiki/Add-a-bank-Account#user-authentication-service)), or does Direct Login only work with OAuth?

As a use case, I have an app that already has a login/register service which I want to link to, and I want to open a bank account for my users and I want to use the API for them.

With the normal OAuth w/ third party authentication flow, that would still require me to have them log in once for my app and then again for Open Bank Project. Would using Direct Login use my authentication service or Open Bank Project's? If it doesn't use mine, is it possible to make it? This use case should be documented.

**Comment by simonredfern** [comment]
Slack is the place for such questions! I see you there already! (briefly, DirectLogin is a simple point to point login process)

**Comment by edenworky** [comment]
Yes! I realized after the fact. Sorry 😅
