### ISSUE TITLE
Remove spam in the issue tracker. 

### ISSUE THREAD

**Issue by RokeJulianLockhart** [OpenBankProject/OBP-API#2378]
1. https://github.com/OpenBankProject/OBP-API/issues/2064#issue-1237540019
2. https://github.com/OpenBankProject/OBP-API/issues/2044#issue-1221937275
3. https://github.com/OpenBankProject/OBP-API/issues/2045#issue-1222033042
4. https://github.com/OpenBankProject/OBP-API/issues/2056#issue-1227800133
5. https://github.com/OpenBankProject/OBP-API/issues/2058#issue-1228649587

You shan't be treated seriously with such abysmal moderation.

**Comment by simonredfern** [comment]
Good point, we will close them.
