### ISSUE TITLE
Make sure swagger validates with Swagger Tools

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#25]
Swagger output is not validating e.g.
https://enbdg.openbankproject.com/obp/v1.4.0/resource-docs/v2.0.0/swagger

This should probably validate in various Swagger clients e.g:
http://editor.swagger.io/#/
http://bigstickcarpet.com/swagger-parser/www/index.html

**Comment by marko-md** [comment]
Git version: c1e7771
Git commit message: JobRequest verb changed to lowercase

**Comment by marko-md** [comment]
Still remains 
✖ Swagger Error
Relative paths to the individual endpoints. They must be relative to the 'basePath'.
Jump to line 17 
i.e. 
  "paths": {
    "": {
      "get": {
produce the error
and 
  "paths": {
    "/": {
      "get": {
do not produce the error
