### ISSUE TITLE
Enforce Strong passwords

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#253]
both on register page and API call to create users.

Allow two forms of password:

1) Rather long phrase to allow something like "paperseatblueberlin" i.e. > 16 characters
and
2) Min 10 characters with mixed numbers + letters + upper+lower case + at least one special character. 

Ref:PB10

**Comment by hongwei1** [comment]
![image](https://cloud.githubusercontent.com/assets/23308710/23747424/e03a1aaa-04bf-11e7-88a3-cd52c608372f.png)
The wrong case
