### ISSUE TITLE
Generate consumer registration form with liftweb.http.SHtml

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#271]
See https://exploring.liftweb.net/master/index-6.html

Ref:PB3
Ref:PB4

**Comment by simonredfern** [comment]
@marko-md Please review

**Comment by marko-md** [comment]
As far as I can see it's a good work by Hongwei. I will use for #252

**Comment by simonredfern** [comment]
All form elements must be generated by liftweb

**Comment by marko-md** [comment]
@simonredfern Do you point to the button "SEND"?

**Comment by simonredfern** [comment]
@marko-md Yes I meant Submit button
