### ISSUE TITLE
Direct Login Issue

### ISSUE THREAD

**Issue by umamaheshpyla** [OpenBankProject/OBP-API#312]
Its(my/logins/direct) returns like as below.
SuccessOBP-20011: Value contains invalid characters"

When I'm trying to do direct login from my Angular2 application.
my Headers:
Content-Type:application/json
Authorization:DirectLogin username="xxxxxx", password="xxxxxxx", consumer_key="aaaaaaa"

**Comment by BrainFeeder** [comment]
I have same issue.. How did you solve this?

**Comment by BrainFeeder** [comment]
Ah, for me it works when I changed the single quotes to double quotes in the headers ... 

    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
	    "Content-Type: application/json",
	    "Authorization: DirectLogin username=\"".$user."\",password=\"".$password."\",consumer_key=\"".$secret."\""
	));
