### ISSUE TITLE
Refactor the name of type AccountType and/or getBankAccountType

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#33]
In Connector.scala trait Connector we have a type called AccountType which has lead to some unfortunate function names e.g. getBankAccountType.

getBankAccountType should be renamed getBankAccount because it gets an account not the "type" of the account. Otherwise its confusing becuase we mix up type (as in CURRENT, MORTGAGE etc.) with the Scala Type.

Let's wait until Scala 2.11 has been merged in before making this change.

**Comment by pbozin** [comment]
Refactored method name getBankAccountType to getSingleBankaccount
