### ISSUE TITLE
Add GET request to query users by username (and email)

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#333]
e.g.
/users?username=joeblogs
/users?email=joe@example.com

(we should replace the existing URL for querying user by EMAIL)

**Comment by constantine2nd** [comment]
Get User by USERNAME:
https://apiexplorersandbox.openbankproject.com/#OBPv3_0_0-getUserByUsername
Get Users by Email Address:
https://apiexplorersandbox.openbankproject.com/#OBPv3_0_0-getUser
