### ISSUE TITLE
Investigate user not activated on login

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#338]

**Comment by hongwei1** [comment]
![emailvalidation](https://cloud.githubusercontent.com/assets/23308710/22327479/b23cb884-e3b7-11e6-9991-bbb0fb828ac6.png)

This one should be helpful

**Comment by hongwei1** [comment]
![login_kafak](https://cloud.githubusercontent.com/assets/23308710/22417209/7616dd16-e6d3-11e6-84d5-1c1953a62bc5.png)

I find the problem in Kafka mode.
The user can only login in once.
Logout , and then login in , it will show the validated error massage.

**Comment by simonredfern** [comment]
The error also has been seen in Mapped connector

**Comment by simonredfern** [comment]
Check the test situation with this. Test via API Explorer?

**Comment by simonredfern** [comment]
No recent reports of this.
