### ISSUE TITLE
Get account information

### ISSUE THREAD

**Issue by AlbertRenat** [OpenBankProject/OBP-API#34]
I want to get bank account from account information of Open Bank Project in adroid sdk.
Also I want to know relation between OBP accoutn and reall bank accout.
Please help.

**Comment by simonredfern** [comment]
Please use the API Explorer to explore the API:

 https://apiexplorersandbox.openbankproject.com/

For instance this call:

https://apiexplorersandbox.openbankproject.com/#2_0_0-accountById

Most of the account information comes from the bank (in non sandbox mode) (but not the account_id this is a UUID)

Let us know if you have other questions. You can also join our slack channel (we need your email for that)

**Comment by simonredfern** [comment]
hi @AlbertRenat Thanks for your question When OBP is connected to a core banking system. bank_id represents a real bank (i.e. a bank within a group) account_id maps to an account which is held at the bank identified by bank_id. Hope that helps. Please join our slack channel using https://slack.openbankproject.com/ for further questions.
