### ISSUE TITLE
Add GET  for transaction-type charges

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#344]
Extend getTransactionRequestTypes (currently in 1_4_0) (ONLY add new attributes / objects). (Else create a new version.)

Thus:

/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transaction-request-types

should also return charges info as found in transaciton request.

However, the charges info should come from connector so we'll use the following as the starting point for getTransactionRequestTypes which is already in Connector.scala:

protected def getTransactionRequestTypesImpl(fromAccount : BankAccount) : Box[List[TransactionRequestType]] 

We'll need to persist the TransactionRequestType

In Mapped connector, store:
id
name (e.g. SANDBOX_TAN, SEPA etc.) 
bank_id
charge_currency
charge_amount
charge_summary 

Then getCurrentChargeValue(bankId, accountId, viewId, transactionRequestTypeName) : Box[Charge] will get the Charge from the TransactionRequestType table in Mapped connector, else Kafka etc.
In Mapped, we will ignore accountId, viewId for now.

**Comment by simonredfern** [comment]
Just Mapped. We need Kafka

**Comment by simonredfern** [comment]
For mapped, if no charges data in database, a default will be returned. For Kafka, a response is required.

**Comment by hongwei1** [comment]
All mapper ,OBP-JVM and Kafka have the default value.
