### ISSUE TITLE
Add API call to Link User to Customer

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#35]
Currently we store the user_id of a Customer in the Customer object. But in the case we get customer from the bank, we don't want to have to (and probably cannot) write a user_id to the bank's customer.

Thus we're creating a new object which links a user with a customer for a bank.

It will contain:

user_id
customer_id
bank_id
date_inserted
is_active (Boolean defaults to True)

To start with we'll 
POST to /banks/BANK_ID/UserCustomerLinks

and it will use the currently logged in User

We'll need to modify:

object MappedCustomerProvider extends CustomerProvider {

  override def getCustomer(bankId : BankId, user: User): Box[Customer] = {
    MappedCustomer.find(
      By(MappedCustomer.mUser, user.apiId.value),
      By(MappedCustomer.mBank, bankId.value))
  }

etc. So that we look at UserCustomerLink.

Add a script to migrate the data.

**Comment by pbozin** [comment]
> [Friday, May 20, 2016 10:28:04 AM Simon Redfern] one thing: 
we should make sure we don’t confuse customer_id and customer_number. customer_id should be a UUID / id generated by OBP (or the bank). Customer_number should be the internal customer_number the bank / customer uses. I.e. customer_id can go in urls but customer_number must not. so in UserCustomerLinks we should use user_id and customer_id
