### ISSUE TITLE
tighten OAuth config.

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#352]
Probably should throw error if hostname is not set (probably already earlier in code)       

//prepare the base string (should we really have openOr here?)
       var baseString = httpMethod+"&"+URLEncoder.encode(Props.get("hostname").openOr(S.hostAndPath)  + S.uri ,"UTF-8")+"&"

**Comment by simonredfern** [comment]
also add further comments e.g. for def makeParamsPart(): List[(String, String)] = {

**Comment by marko-md** [comment]
@simonredfern makeParamsPart() was renamed to urlParameters() and added a comment in a commit named "4550600 Marko Milic on 1/23/17 at 9:44 AM OAuth1.0 - fixed url checksum to include GET parameters, added comments"
