### ISSUE TITLE
Metrics. Add the following to logAPICall / Metrics:

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#371]
Add the following to logAPICall / Metrics:

	implemented_by_partial_function (name of the Scala Partial Function being used for the endpoint)
	implemented_in_version (name of version where the call is implemented)
	consumer_id (not key)
	verb (GET, POST etc.)

**Comment by hongwei1** [comment]
implemented_by_partial_function not support yet
