### ISSUE TITLE
Metrics. Add GET /management/metrics

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#374]
Metrics. Add GET /management/metrics
	Require CanReadMetrics Role

**Comment by simonredfern** [comment]
Enforce maximum limit to 10000

**Comment by hongwei1** [comment]
"Enforce maximum limit to 10000" ->   #453.

**Comment by marko-md** [comment]
Commit: [Set a maximum of limit of 10000](https://github.com/marko-md/OBP-API/commit/c59960d714c8a6ca9040af3fd9e4bc1e7c18c7e3)
