### ISSUE TITLE
Metrics. Filters Part 2. Add url string *filtering* (no wilde cards etc.) parameters to GET /management/metrics

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#376]
Should  be able to filter on:

 consumer_id
 user_id (if null ignore)
 anon true => return where user_id is null. 
 	  false => return where
 	  (if null ignore)  
 url (if null ignore)
 app_name (if null ignore)
 implemented_by_partial_function (if null ignore)
 implemented_in_version (if null ignore)
 verb (if null ignore)

**Comment by hongwei1** [comment]
0b7b022
