### ISSUE TITLE
Cannot create transaction using POST

### ISSUE THREAD

**Issue by DavidDon13** [OpenBankProject/OBP-API#38]
Hi guys, love the api. great job! I'm running into a POST error in nodejs when I try to make a transaction.

consumer.post("https://apisandbox.openbankproject.com/obp/v2.0.0/banks/hsbc-test/accounts/" + req.params.senderId + "/owner/transaction-request-types/SANDBOX_TAN/transaction-requests",
            oauthToken,
            foauthTokenSecret,
            obj,
            function (error, data, response) {
                if (error) {
                    console.log("Something went wrong: " + error.statusCode + " " + error.stack);
                    res.status(404).send(null);
                }else{
                    try {
                        console.log(JSON.parse(data));
                        var parsedData = JSON.parse(data);
                        res.status(200).send(parsedData);
                    }catch(Exception) {
                        console.log(Exception);
                        res.status(400).send("Couldn't parse data" + Exception);
                    }
                }

```
        });
```

I keep getting a generic 404 error. Please help!

**Comment by simonredfern** [comment]
Hi. Please see this Python example. Hope that helps. If not please get back to us.

https://github.com/OpenBankProject/Hello-OBP-DirectLogin-Python/blob/master/hello_payments.py

**Comment by simonredfern** [comment]
@somanole please have a look at the possible cause of this error

**Comment by simonredfern** [comment]
@somanole at some point!
