### ISSUE TITLE
Tests fail if there is no src/main/resources/git.properties

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#40]
Presumably since git-commit-id-plugin was disabled, running 

```mvn test```

fails if  there is no _src/main/resources/git.properties_ . It probably went unnoticed, because the file is ignored via _.gitignore_ and systems which ran tests prior to the disabling commit have that file. Move it away and you should see an error like:

```
2016-05-30 17:49:35,138 [qtp1959910454-74] WARN  code.api.util.APIUtil  - gitCommit says: Could not return git commit. Does resources/git.properties exist?
2016-05-30 17:49:35,138 [qtp1959910454-74] ERROR code.api.util.APIUtil  - Exception in gitCommit: java.lang.NullPointerException
```

I assume the tests need fixing.

**Comment by sebtesobe** [comment]
The tests run fine now on our CI and we can deploy again, yay!

@pbozin , i was just asked by @simonredfern to reenable **git-commid-id-plugin** in _pom.xml_, because it is used by e.g. https://unicredit.openbankproject.com/obp/v1.4.0/root . Could you please try to explain why it was disabled by commit 1adb333fd8e4a2de3d99372409dc516aa6c678d2 in the first place and if we can have it enabled (or disabled) for good? Previously it was reenabled by you and then disabled shortly after by @simonredfern and it all seems to be a bit of a mess now.

**Comment by pbozin** [comment]
git-commid-id-plugin in pom.xml was disabled by commit 1adb333 because container build failed complaining about maven3 being required instead of maven2. The issue was resolved by updating obp-base container to use maven3.
