### ISSUE TITLE
status in connector.scala documentation / check

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#400]
•	Irrespective of what the amount is and what the limit returned by getChallengeTreshold was the transaction stays in the initiated status. This however should be done only if the amount is different than the getChallengeThreshold. 

Document transaction_status_scheduler_delay - or move into specific connector?

   // TODO Document this
        if ( Props.getLong("transaction_status_scheduler_delay").isEmpty )
          TransactionRequests.STATUS_COMPLETED
        else
          TransactionRequests.STATUS_PENDING
      } else {
        TransactionRequests.STATUS_INITIATED
      }

**Comment by hongwei1** [comment]
checked the statues stuff over Mapper and Kafka, it is working

**Comment by simonredfern** [comment]
Also commented the block of code. Related ticket is https://github.com/OpenBankProject/OBP-API/issues/446 since the Kafka connectors need to send a message to check status of the Transaction Requests
