### ISSUE TITLE
Add bank level entitlements / roles

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#42]
1)

Define Super Admin Users via Props (not database so we don't have to edit database)

e.g.

super_admin_user_ids=234hkjhkjhwer,asdhfjaksjhdf23423764,asdfjkjhasdfasdf

2) Create function to check 
def isSuperAdmin(user_id) : Boolean
.. look in Props and compare user_id

This is at the API instance level (not bank)

3) Roles in code

Roles should be easily definable in code by programmers who will use them to guard API endpoints and functions e.g:

in file Role.scala

val canSearchAllTransactions : Role = "canSearchAllTransactions"
val canSearchAllAccounts : Role = "canSearchAllAccounts"
val canQueryOtherUser : Role = "canQueryOtherUser"

Question: val role : Role = "role" the best way to do this?

4) Define Trait/Class and Mapper Table "Entitlement"
Entitlement is the link between User (and Bank) and Role
i.e. A User has zero or more Roles at a Bank.

bankId: String
userId : Sting (UUID)
roleName : String

5) POST /users/USER_ID/entitlements
{
"bank_id" : "bank-x",
	"role_name": "roleCanQueryUser"

}
To POST here we assert isSuperAdmin(user_id)

6) GET /users/USER_ID/entitlements
[{
	"entitlement_id": "qiuyuroiuywueioriuy",
	"role_name": "roleCanQueryUser",
"bank_id":"bank_x"
}]
To GET here we assert isSuperAdmin(user_id)

7) DELETE /users/USER_ID/entitlements/qiuyuroiuywueioriuy
To DELETE here we assert isSuperAdmin(user_id)

8) 
Add function:
def hasEntitlement(bankId, userId, roleName : Role) (roleName is type safe)
check in database entitlements table

9) Use hasEntitlement(bankId, userId, roleName) in API calls etc.

**Comment by marko-md** [comment]
Still have to do:
7) DELETE /users/USER_ID/entitlements/qiuyuroiuywueioriuy
To DELETE here we assert isSuperAdmin(user_id)

**Comment by simonredfern** [comment]
Petar can you do 7) or Marko?

**Comment by simonredfern** [comment]
Working

**Comment by marko-md** [comment]
6) GET /users/USER_ID/entitlements returns
"list":[{
    "entitlement_id":"5f7d5cb8-1dfa-4d19-a632-6962066ece47",
    "user_id":"87dc2710-12f0-4590-a62d-f1194268c1d6",
    "role_name":"CanQueryOtherUser"
  }]
instead of
"list":[{
    "entitlement_id":"5f7d5cb8-1dfa-4d19-a632-6962066ece47",
    "role_name":"CanQueryOtherUser",
    "bank_id":"obp-bank-x-gh1"
  }]
