### ISSUE TITLE
Consumer registration - Optional more information url displayed to user

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#433]
When a user registers an applicaiton we need the option to show a more information link to the user.

Thus

1) Add post_consumer_registration_more_info_url to Props (default = None)

2) Add post_consumer_registration_more_info_text to Props (default = None)

3) After the consumer is registered, in the info screen (that shows consumer key etc) if post_consumer_registration_more_info_url is Full, also show the url as a link with the text: post_consumer_registration_more_info_text (default text "Please see the following page")

4) Also send the url and text as an email to the user.

**Comment by hongwei1** [comment]
![image](https://cloud.githubusercontent.com/assets/23308710/23714150/7eb1c590-0428-11e7-9fb7-b365d066e960.png)
Done

**Comment by simonredfern** [comment]
Display logic better now but still need the link to be clickable. See the TODO in ConsumerRegistration.scala

**Comment by simonredfern** [comment]
formatting fixed with f3a9a6a097d2fb42b0463e6dedeb9c9b0238f497
