### ISSUE TITLE
API Documenation is hard to read - Use Slate?

### ISSUE THREAD

**Issue by JamieFarrelly** [OpenBankProject/OBP-API#439]
![image](https://cloud.githubusercontent.com/assets/12645106/23703048/e3608612-03f5-11e7-917e-9090732ed113.png)

It's fairly difficult to read the side menu on the left, at first I thought it was just on mobile that the documentation was a bit dodgy but even on desktop the text is well too small in the side menu. Surely it's worth considering something like [slate](https://github.com/lord/slate) which is perfect for this type of thing - and mobile friendly.

**Comment by simonredfern** [comment]
Hi @JamieFarrelly We also provide a Swagger definintion so it would be possible to also use somehting like slate. But API Explorer will remain. There's a ticket here where I've added your note: https://github.com/OpenBankProject/API-Explorer/issues/1
