### ISSUE TITLE
Metrics performance on busy sandbox

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#453]
I can reliably kill a sandbox with more than 4 million rows in the metrics database table when asking for `/management/metrics`.

According to @hongwei1 , the scala code loads all rows into memory at once before filtering down to the limit's 200.

**Comment by hongwei1** [comment]
may be useful 

val currentDate = new Date()
val timeLimit = new Date(currentDate.getTime - 1000 * 60 * 60 * 24 * 2)
  
MappedMetric.findAll(By_<(MappedMetric.date, currentDate),
                         By_>(MappedMetric.date, timeLimit))

 MappedMetric.findAll(StartAt(0), MaxRows(1000))
