### ISSUE TITLE
Improve depth of Swagger definition for certain endpoints

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#471]
1	/accounts
2	/my/accounts
3	/banks/BANK_ID/accounts
4	/banks/BANK_ID/accounts/private
5	/my/banks/BANK_ID/accounts/ACCOUNT_ID/account
6	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/account
7	/users/current
8	/banks
9	/banks/BANK_ID
10	/banks/BANK_ID/customer
11	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions
12	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/transaction
13	/my/banks/BANK_ID/accounts/ACCOUNT_ID/transactions
14	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transaction-request-types
15	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transaction-request-types/TRANSACTION_REQUEST_TYPE/transaction-requests
16	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transaction-request-types/TRANSACTION_REQUEST_TYPE/transaction-requests/TRANSACTION_REQUEST_ID/challenge
17	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transaction-requests
18	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/counterparties
19	/banks/BANK_ID/accounts/ACCOUNT_ID
20	/banks/BANK_ID/accounts/ACCOUNT_ID/views
21	/banks/BANK_ID/accounts/ACCOUNT_ID/views
22	/banks/BANK_ID/accounts/ACCOUNT_ID/views/VIEW_ID
23	/banks/BANK_ID/accounts/ACCOUNT_ID/views/VIEW_ID
24	/banks/BANK_ID/accounts/ACCOUNT_ID/permissions/PROVIDER_ID/USER_ID/views
25	/banks/BANK_ID/accounts/ACCOUNT_ID/permissions/PROVIDER_ID/USER_ID/views/VIEW_ID
26	/banks/BANK_ID/accounts/ACCOUNT_ID/permissions/PROVIDER_ID/USER_ID/views/VIEW_ID
27	/banks/BANK_ID/accounts/ACCOUNT_ID/permissions/PROVIDER_ID/USER_ID/views
28	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/counterparties
29	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/other_accounts
30	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/other_accounts/OTHER_ACCOUNT_ID
31	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/metadata/narrative
32	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/metadata/comments
33	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/metadata/comments/COMMENT_ID
34	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/metadata/tags
35	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/metadata/tags/TAG_ID
36	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/metadata/images
37	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/metadata/images/IMAGE_ID
38	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/metadata/where
39	/banks/BANK_ID/accounts/ACCOUNT_ID/VIEW_ID/transactions/TRANSACTION_ID/other_account
40	/fx/FROM_CURRENCY_CODE/TO_CURRENCY_CODE
41	/banks/BANK_ID/accounts/ACCOUNT_ID/permissions
42	/banks/BANK_ID/accounts/ACCOUNT_ID/permissions/PROVIDER_ID/USER_ID
43	/banks/BANK_ID/customers

**Comment by hongwei1** [comment]
fixed in #511
