### ISSUE TITLE
https://openbankproject.com/for-developers/ has outdated link?

### ISSUE THREAD

**Issue by sohrabsaran** [OpenBankProject/OBP-API#507]
Opening para of https://openbankproject.com/for-developers/ says: 
Want to develop a financial application which accesses bank account transactions? The Open Bank Project offers an easy-to-use [RESTful JSON API](https://github.com/OpenBankProject/OBP-API/wiki/REST-API-V1.2.1). Connect in minutes and start using it.

Is this the latest stable API? If not then should the link be updated to point to some page that:
- lists the various stable releases and links to their feature-set/compatibility notes
- starts with the latest stable release?

**Comment by constantine2nd** [comment]
Please use this page as an start point: https://github.com/OpenBankProject/OBP-API
The is no the page https://openbankproject.com/for-developers/ anymore.
