### ISSUE TITLE
Extend /root endpoint to have health_check

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#518]
https://apisandbox.openbankproject.com/obp/v2.2.0/root

Add this to root:

(actor_health should list all actors)
(connector_health should list a few public operations over kafka - to give an indication of connector health)

{
	"actor_health": {
		"consumer": true,
		"metric": false
	},
	"connector_health": {
		"getBanks": true
	}
}

The names e.g. "consumer" are indicative. They should match the actor names
Note: Any sensitive data should go in /config

**Comment by constantine2nd** [comment]
We've added the endpoints:
**Get Adapter Info**
**Get Connector Status (Loopback)**

If there is a need for some more specific health check please open a new ticket.
