### ISSUE TITLE
elasticSearchWarehouse Fix bank check

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#538]
Currently, the partial `elasticSearchWarehouse` in `src/main/scala/code/api/v2_0_0/APIMethods200.scala` is using this line to check the role `CanSearchWarehouse` against a bank:

`b <- tryo{Bank.all.headOption} ?~! {ErrorMessages.BankNotFound}`

It seems this means that the first bank in the database table (not by id!) is used to check if the user has the entitlement granted for this role at this bank. In a conrete sandbox for BNPP the bank `bnpparibas.07.uk` has to be set, but that's rather random, this bank has no more significance than any other bank in that sandbox! (I also had to find out manually which bank to use)

So the questions are:

1. Why have this dependency on a bank for role `CanSearchWarehouse` at all? I believe this is currently unused and causes confusion.
2. If there really needs to be bank for this role,  we would need a way to explicitly define which bank to connect to which warehouse.

@marko-md you added the line of code above, @simonredfern what do you reckon?

**Comment by marko-md** [comment]
@sebtesobe It is done by this commit https://github.com/OpenBankProject/OBP-API/commit/287422919f838ec0dfdbc6b92e0173be16e52263.
Entitlement CanSearchWarehouse requires a bank. If that property is set to false bank will not be considered at all.

**Comment by sebtesobe** [comment]
@marko-md What property needs to be set to false to ignore the bank? Do i then still need to supply a bank when adding an entitlement for role `CanSearchWarehouse`?

**Comment by marko-md** [comment]
@sebtesobe The property is in the code. It cannot be change over props file. As far as I know if some entitlement does not require a bank it is assumed as a system one.

**Comment by sebtesobe** [comment]
Thanks for your swift reply. It seems we are not one step closer to resolve this issue, tho. Maybe @simonredfern has to make a strategic decision. I, for instance, do not know why things are implemented the way they are, but they are a slight pain in the arse.

**Comment by sebtesobe** [comment]
Seems fixed in 587c8d1726b3466c3448f7a72855ee424471069f
