### ISSUE TITLE
Malformed Authorization header does not result in an error

### ISSUE THREAD

**Issue by tb-pq** [OpenBankProject/OBP-API#55]
If a malformed DirectLogin Authorization header is passed, ex. "Bearer 9834ucm34381y4tcm0u34980" then no data is returned, whereas a 400 or 403 would be expected.

**Comment by andrisak** [comment]
In which version did you encounter this? When running on the latest version in the develop branch with the header Authorization: "Bearer 9834ucm34381y4tcm0u34980" the result I see is:

HTTP/1.1 400 Bad Request
`{  "error": "OBP-20002: These DirectLogin parameters are missing: username, password, consumer_key" }`

Do you have any more details that could help me understand the problem better?

**Comment by everett-tesobe** [comment]
Can you provide the got commit? Perhaps you are running docker image which is a bit old?

On 19 June 2016 01:36:42 GMT-07:00, tb-pq <notifications@github.com> wrote:
>If an malformed DirectLogin Authorization header is passed, ex. "Bearer
>9834ucm34381y4tcm0u34980" then no data is returned, whereas a 400 or
>403 would be expected.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenBankProject/OBP-API/issues/55

-- 
Written on small screen. (K9, Fairphone 2)

**Comment by tb-pq** [comment]
It was the BNP Paribas test domain. Sounds like that's fixed elsewhere. (Or my client is doing something very odd.) So I'll close this ticket.
