### ISSUE TITLE
Prevent me from automatically login on API Explorer 

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/OBP-API#56]
On API Explorer, I want to login with a different user. After logout, the API explorer forces me to login  with my previous user credentials. I can't seem to be able to use different credentials unless flushing the cache. 

NB: This might happen on other places ra

**Comment by simonredfern** [comment]
Yes this is an issue with Sofi too. (Any web App using the same browser / session).  @pbozin : Do we need to rename the session cookie?

**Comment by pbozin** [comment]
That happens when user is logged-in in OBP-API in another tab in the same browser where API-Explorer is opened. Can you confirm that this also happens when there is no open tab with OBP-API?

**Comment by constantine2nd** [comment]
Done by a [commitId](https://github.com/OpenBankProject/API-Explorer/commit/e87205940cd488ae05ff375f999e186ebd121c65)
