### ISSUE TITLE
Create getAccounts for V300

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-API#560]
1 Have a look at : Get Accounts at all Banks (Private) --V200
https://apiexplorersandbox.openbankproject.com/?version=3.0.0&list-all-banks=false&core=&psd2=&obwg=&ignoredefcat=&bank_id=gh.29.uk&account_id=8ca8a7e4-6d02-48e3-a029-0b2bf89de9f0#2_0_0-corePrivateAccountsAllBanks

2 modify the response body as following : 
{
  "id":"uk7",
  "label":"CURRENT",
  "bank_id":"rbs",
  "_links":{
    "self":{
      "href":"https://apisandbox.openbankproject.com/obp/v2.0.0/my/accounts"
    },
    "detail":{
      "href":"https://apisandbox.openbankproject.com/obp/v2.0.0/my/banks/rbs/accounts/uk7/account"
    }
  }
}
---------> 
{
  "id":"uk7",
  "label":"CURRENT",
  "bank_id":"rbs",
   "account_routing": {
    "scheme": "OBP_ACCOUNT_ID",
    "address": "8ca8a7e4-6d02-48e3-a029-0b2bf89de9f0"
  }
}

3 and add the tests for that:
Have a look at "class AccountTest"

**Comment by constantine2nd** [comment]
Done.
