### ISSUE TITLE
Add endpoint to list Customers

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#568]
Will need query parameters for filter on customer id, customer number and legal name.

**Comment by constantine2nd** [comment]
We have next endpoint
Get Firehose Customers:
/banks/BANK_ID/firehose/customers

Possible custom URL parameters for pagination:   
sort_direction=ASC/DESC
limit=NUMBER ==> default value: 50
offset=NUMBER ==> default value: 0
from_date=DATE => default value: date of the oldest customer created (format below)
to_date=DATE => default value: date of the newest customer created (format below)

**Comment by constantine2nd** [comment]
We have endpoints:
**Gets all Customers that are linked to a User**
**Get Customers for current User at Bank**
