### ISSUE TITLE
Feature Request: Add copy button to API Explorer

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/OBP-API#58]
Add two buttons to copy the information in the API explorer 
1. Copy URL 
2. Copy JSON Text in the result box

**Comment by ichaib** [comment]
![copy-api-explorer](https://cloud.githubusercontent.com/assets/572870/16176687/207cbc5a-3615-11e6-8048-fc5781a17306.png)

**Comment by simonredfern** [comment]
Please add API Explorer tickets to API Explorer repo issues
