### ISSUE TITLE
Add v3.0.0 GET /users/user_id/USER_ID

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#587]
Add v3.0.0 GET /users/user_id/USER_ID

Add v3.0.0 GET /users/email/EMAIL (should replace v2 /users/USER_EMAIL)

Add v3.0.0 GET /users/username/USERNAME

**Comment by sebtesobe** [comment]
@constantine2nd  Just to avoid confusion: I cannot implement this, but i would test it using the API Manager.

**Comment by constantine2nd** [comment]
@sebtesobe It is ready for testing.

**Comment by sebtesobe** [comment]
@constantine2nd has been successfully implemented in API Manager a few days ago, thanks! I do not mind closing this.
