### ISSUE TITLE
getUser chokes on certain email address TLDs

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#593]
When requesting  `/obp/v3.0.0/users/foo@bar.ai` (call `getUser`), the API throws a 404. There seems to be issues around certain email address TLDs which sometimes also happen on sign up iirc.

**Comment by constantine2nd** [comment]
@sebtesobe Does API means  API Manager in the comment above? I cannot reproduce the issue in API Explorer.

**Comment by sebtesobe** [comment]
@marko-md What email address are you using on what sandbox. I also noticed one email address which was actually working when using API Explorer, but producing a 404 through API Manager.

**Comment by constantine2nd** [comment]
@sebtesobe @simonredfern It seems that the problem cause the next fact about file extension:

> Adobe Illustrator Artwork (AI) is a proprietary file format developed by Adobe Systems for representing single-page vector-based drawings in either the EPS or PDF formats. The .ai filename extension is used by Adobe Illustrator. The AI file format was originally a native format called PGF.

In other words in url http://localhost:8080/users/email/you@example.ai ".ai" will be treated as a file extension.

We have two solutions in this case:
1. To use LiftRules.explicitlyParsedSuffixes = Helpers.knownSuffixes - "ai"  - **Has to be applied for each particular case**
2. To rearrange http://localhost:8080/users/email/you@example.ai to http://localhost:8080/users/email/you@example.ai/send for instance  - **General solution**

**Comment by simonredfern** [comment]
I would prefer a terminator something like http://localhost:8080/users/email/you@example.ai to http://localhost:8080/users/email/you@example.ai/terminator - because then it is generic and will always work.

**Comment by constantine2nd** [comment]
@sebtesobe @simonredfern This is ready for testing. API Manager should use version 3.0.0

**Comment by sebtesobe** [comment]
Looking good, thanks!
