### ISSUE TITLE
OBP20006 User does not have a role cangetconsumers

### ISSUE THREAD

**Issue by jeremykyc** [OpenBankProject/OBP-API#594]
OBP20006 User does not have a role cangetconsumers

 I reckon you also won't be granted that entitlement. But can you get your own consumer: https://bnpparibas-apiexplorer.openbankproject.com/?version=3.0.0&list-all-banks=false&core=&psd2=&obwg=&ignoredefcat=#2_1_0-getConsumer

no Get Consumer is throwing the same error

PROJECT TestKYC 
USER jeremykyc

I guess the API call uses the same guard for `getConsumer` as for `getConsumers`, although imho it does not need to if you are requesting your own consumer. Do you want to create a ticket for that on https://github.com/OpenBankProject/OBP-API/issues/, giving a use-case why you would want this to be available for non-admin users?

**Comment by simonredfern** [comment]
Hi, So far getConsumer and getConsumers has been for an "API admin" using the API Manager to view the Consumer information. Note that neither of these calls return the consumer key or secret. 

However, I can imagine a usecase where the user that created the Consumer could see the details e.g. for the enable status or to check the redirect url.

**Comment by constantine2nd** [comment]
We've added endpoint **Get the Consumers for logged in User**
It's not guarded by the role.
