### ISSUE TITLE
Feature Request: Add load icon to the API Explorer

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/OBP-API#60]
When clicking on  a GET or POST button on the API explorer, show a small loading icon to inform the users that the query is being processed.

**Comment by simonredfern** [comment]
Nice idea but - Please add API Explorer tickets to API Explorer repo issues

**Comment by simonredfern** [comment]
This was added to API Explorer issues:  https://github.com/OpenBankProject/API-Explorer/issues/9
