### ISSUE TITLE
Add Slack Auto-invite

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/OBP-API#61]
Allow people to register themselves on openbankproject.slack.com instead of admin adding each individual manually. See here for an example https://github.com/outsideris/slack-invite-automation

**Comment by simonredfern** [comment]
Nice idea but not related to this repository.

**Comment by Horizon88** [comment]
@simonredfern not sure where to ask this but Can you white label Kyc-chain.com before you close this issue :-)

**Comment by simonredfern** [comment]
This issue not related to this repo
