### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by bobvanluijt** [OpenBankProject/OBP-API#612]
Hi all,

Awesome project. Quick question, is there some sample data available that I can use to do some research? I'm interested to see the inner workings and some demo data would be awesome.

Thanks

**Comment by simonredfern** [comment]
Hi !

You can use the general sandbox at https://apisandbox.openbankproject.com/

For other general questions, please join our slack channel via:

https://slack.openbankproject.com/

Thanks!
