### ISSUE TITLE
getConnectorMetrics start_date does not work for current day

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#618]
If you call `/management/connector/metrics` with parameter `start_date`, it is not possible to get data for the current day, only for days in the past.
See https://apisandbox.openbankproject.com/obp/v3.0.0/management/connector/metrics?start_date=2017-06-30 (adjust for today when testing!). 2017-06-29 (previous day) returns data. The database does contain data for the current day.

**Comment by constantine2nd** [comment]
Fixed.
