### ISSUE TITLE
Add balance to get_accounts response  	

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/OBP-API#62]
Add balance to the current response of /banks/BANK_ID/accounts
so it looks like something:
[{
  "id":"SHARED",
  "label":null,
  "views_available":[{
    "id":"owner",
    "short_name":"Owner",
    "is_public":true
    **"balance": XXX**
  }],
  "bank_id":"obp-bank-x-gh"
},

**Comment by simonredfern** [comment]
The reason its not there at the moment is because we're not specifying the view with this call. Could perhaps show it if the user has access to a view which shows the balance.

**Comment by constantine2nd** [comment]
Done.
Get Account by Id (Full) has balance.
