### ISSUE TITLE
getConnectorMetrics filter connector_name does not seem to work

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#620]
Trying to filter the output via connector_name does not seem to work:

https://apisandbox.openbankproject.com/obp/v3.0.0/management/connector/metrics?start_date=2017-06-29 returns plenty of data. But:

https://apisandbox.openbankproject.com/obp/v3.0.0/management/connector/metrics?start_date=2017-06-29&connector_name=LocalMappedConnector$

-> `Bad response code (401) from OBP API server: {"error":"Invalid signature"}`

https://apisandbox.openbankproject.com/obp/v3.0.0/management/connector/metrics?start_date=2017-06-29&connector_name=LocalMappedConnector

-> `{
  "metrics":[]
}`

**Comment by constantine2nd** [comment]
Due to continuous enhancements of the app this issue cannot be reproduced anymore.
