### ISSUE TITLE
Reduce lengths of ID columns. 

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#642]
This is to accomodate MySQL which has max index size e.g.: 

CREATE UNIQUE INDEX mappedbranch_mbankid_mbranchid ON mappedbranch ( mbankid, mbranchid )
java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 3072 bytes

Many of our ids are 255 in length but only need to be 36 to support UUID.

**Comment by constantine2nd** [comment]
@simonredfern Many of our ids are using DefaultStringField which is 2000 chars in length.

**Comment by simonredfern** [comment]
Fixed with 1a1513a59fd6c87371ca709abf5c04b123b43094
