### ISSUE TITLE
Refactor updateUserAccountViews

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#646]
updateUserAccountViews needs to be simpler and more functional and call smaller functions.
The internal functions should probably return the objects they create.

updateUserAccountViews (user, List[Accounts]) should not be complicated. It should only need to call three functions:

========
1) getOrCreateAccountView (account, view) # We should cache this function because the available views on an account will change rarely.

This will insert a View (e.g. the owner view) for an Account (BankAccount)

Note: updateUserAccountViews would call createAccountView once per View specified in the IncomingAccount from Kafka.

=========
2) getOrCreateViewPrivilege (account, view, user) #Cache this function 

This gives the user access to the view on the account.

See and or rename and improve addPermission in MapperViews.scala

=======
3) getOrcreateAccountHolder (user, account) #Cache this function 

This makes the user an owner / holder of the account. They need this if they want to create other views (and currently also create transaciton requests)

See createAccountHolder

**Comment by hongwei1** [comment]
If possible, we also need link the userId<-->Customer here. 

createUserCustomerLink
