### ISSUE TITLE
400 returned where 403 was expected

### ISSUE THREAD

**Issue by fergalo** [OpenBankProject/OBP-API#691]
Permission exception message issue:
When access to a resource is denied due to permission restrictions a 403 should be returned, not a 400.

Example:
GET https://apisandbox.openbankproject.com/obp/v3.0.0/banks/rbs/customers/182c9b51-13fd-434a-8307-48d46c5eab67/social_media_handles

![incorrect_response_code](https://user-images.githubusercontent.com/30432323/28920795-413f738c-784b-11e7-85f4-9f60de680e4d.png)

Got

```
400 Bad Request 

{
  "error": "OBP-20006: User is missing one or more roles: CanGetSocialMediaHandles"
}
```

With a message like this would expect the response code to be 

403 Forbidden
The request was valid, but the server is refusing action. The user might not have the necessary permissions for a resource, or may need an account of some sort.

**Comment by constantine2nd** [comment]
Fixed.
