### ISSUE TITLE
Deprecated method "get" of Lift framework 2.6

### ISSUE THREAD

**Issue by marko-md** [OpenBankProject/OBP-API#70]
Behaviour of method "get" of next Lift framework 3.0 release candidate

``` scala
 /**
   * Exists to avoid the implicit conversion from `Box` to `Option`. Opening a
   * `Box` unsafely should be done using `openOrThrowException`.
   *
   * This method '''always''' throws an exception.
   */
  final def get: DoNotCallThisMethod = {
    throw new Exception("Attempted to open a Box incorrectly. Please use openOrThrowException.")
  }
```

We use deprecated method "get" in OBP-API  which will '''always''' throw an exception in next release candidate.
@simonredfern  Please add your thoughts

**Comment by simonredfern** [comment]
Yes, we need to fix those warnings.

**Comment by simonredfern** [comment]
@marko-md Please can you provide *one* before (get) and after (map, flatmap etc.) example and lets see how easy it will be to change all those occurances.

**Comment by marko-md** [comment]
```scala
// Before
bank <- tryo(Bank(bankId).get) ?~! {ErrorMessages.BankNotFound}
//After
bank <- Bank(bankId) ?~! {ErrorMessages.BankNotFound}
```
There is no need to use the method get in this case. For comprehension knows how to get a value from the type of Box.

There are still different kind of warnings we have to fix them. In order to fix they I have to know how to test re-factored code.

**Comment by simonredfern** [comment]
please look at one warning at a time. if there is a test for that code path, refactor and run test. Else add an issue to add a test.

**Comment by constantine2nd** [comment]
We upgraded develop branch to lift version 3.1.0
The issue can be closed.
