### ISSUE TITLE
Refactor ApiRole.scala

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#715]
We have too much duplicaiton of Role names in this file. 

Its easy to define a role: 

  case object CanCreateCustomerAtAnyBank extends ApiRole{
    val requiresBankId = false
  }

but its easy to forget to add it to: 

  def valueOf(value: String): ApiRole = value match {.....

or:

  val availableRoles = ...

Ideally we should be able to define the role once and not have to add it to three places in the code.

**Comment by constantine2nd** [comment]
@simonredfern  Please take a look. We get rid of String type and make "def valueOf" generic. I am not sure that further optimisation regarding "val availableRoles" can bring us enhancement.

**Comment by constantine2nd** [comment]
@simonredfern Read for testing.
