### ISSUE TITLE
Figure out how to separate login state on OBP API / Explorer / Sofi

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#73]
Currently if a user is logged in on the API, if in the same browser, the user will not be prompted for credentials when logging in on the API Explorer. 

This also means that if you want to logout of API Explorer, you have to logout on the API and Explorer.

All three Apps use JESSIONID cookie but it seems to be sub.domain specific.

**Comment by constantine2nd** [comment]
Use **New Private Window** via Firefox or **New incognito window ** via Chromium
