### ISSUE TITLE
Which API spec is the project following?

### ISSUE THREAD

**Issue by bbozo** [OpenBankProject/OBP-API#759]
I'm coming from [here](https://stackoverflow.com/questions/46341494/where-to-find-the-psd2-technical-specification),

as far as I understand, PSD2 is supposed to be a uniform EU-wide standard, and there's a million whitepapers, video blogs, impact estimates, high level overviews, but no technical specification.

Nothing saying really what message needs to be sent where and then happens what. The closest thing I found is this project but even here there's no reference, nothing to imply what exact technical spec you followed.

Could you maybe include it in the project docs? :) I would expect a source from some of the EU's agencies?

**Comment by gintautassulskus** [comment]
Hi @bbozo, I am wondering about this as well. Could you please point me to the document that says that the specification is supposed to be a uniform EU-wide standard?

As far as I know/understand, the directives do not cover the REST API spec, meaning that it is up to each bank to define the spec.

**Comment by simonredfern** [comment]
Hi @bbozo and @gintautassulskus 

Thanks for the questions.

Regarding the current status, Open Bank Project API develop branch currently supports OBP API specs 1.2.1 through 3.0.0

We also have an ISO20022 connector (PAIN) for initiating payments. 

You can read the OBP specs here:  

https://apiexplorersandbox.openbankproject.com/ 

or use the Swagger:

https://apisandbox.openbankproject.com/obp/v1.4.0/resource-docs/v3.0.0/swagger

 or Resource Docs (our own format):

https://apisandbox.openbankproject.com/obp/v1.4.0/resource-docs/v3.0.0/obp

(the Swagger / Resource Doc links can also be found at the bottom of the API Explorer)

Regarding PSD2, PSD2 doesn't explain exactly how countries should comply (e.g. it doesn't define URLs etc.). However, it does say in Article 28 point 3: "Account servicing payment service providers shall also ensure that the dedicated interface uses ISO 20022 elements, components or approved message definitions, for financial messaging". 

This is why STET (the recent French standard) uses field names like "PmtTpInf", "InstrPrty",  "SvcLvl" and "Cd" etc.

In addtion to the OBP standards mentioned above, we aim to support:
1) An ISO 20022 version of OBP. This will most likely be requested using a different Mime type on the current OBP URLs and will be implemented as an automatic translation of OBP terms to ISO20022 equivelents (where they exist). We'll probably support ISO20022 short field names and also longer type names (which are verbose but are more self describing).
2) UK Open Banking standard
3) STET (French)
4) Other Country standards.

Thus OBP API will be able to surface multiple standards using one OBP instance and backend connector. It will provide easy to use REST APIs (OBP) and less easy to read ISO20022 interfaces for compliance.

Hope that helps.

**Comment by bbozo** [comment]
@simonredfern thank you for an excellent explanation :-) I will study it further :-)

**Comment by gintautassulskus** [comment]
Much appreciated, @simonredfern.

**Comment by tiero** [comment]
when gRPC/Protobuf?
