### ISSUE TITLE
Consider MIME type that converts OBP <-> ISO20022 short field names

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#766]
Consider a MIME type that converts OBP JSON field names to ISO20022 short name equivilents and visa versa.

i.e. OBP field name <-> ISO20022 field name

e.g. 

Currency <-> Ccy
Amount <-> Amt

**Comment by constantine2nd** [comment]
Implemented.
E.g. 

1. if we provide an URL **obp/v2.1.0/users/current/customers?format=ISO20022** JSON response is changed from "currency":"EUR" to "ccy":"EUR".

2. If we provide an URL **obp/v2.1.0/users/current/customers?format=OBP** JSON response is changed from "ccy":"EUR" to "currency":"EUR".

3. All other cases do not change JSON response.
