### ISSUE TITLE
v2.0.0 createCustomer rules

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#77]
createCustomer should be callable in these situations:

1) User has CanCreateCustomer (this is already OK)
2) User is same as USER_ID specified (i.e. can create a customer for themself)

Also, if USER_ID is zero length string ("") it should default to the logged in user. (see v2.0.0 createAccount for this logic)

**Comment by simonredfern** [comment]
This should be modified so that:
If a User has CanCreateCustomer they can create a Customer and Link to any User
If a User does not have CanCreateCustomer they can Customer but only link to themself

**Comment by simonredfern** [comment]
And this should be atomic so a User cannot create hundreds of orphaned Customers

So one of the first guards should be to check the UserCustomerLink

**Comment by simonredfern** [comment]
Let's make this simpler: Only allow Customer creation if user has CanCreateCustomer Role

**Comment by marko-md** [comment]
It has been simplified. Current behaviour requires next entitlements:
- CanCreateCustomer
- CanCreateUserCustomerLink
