### ISSUE TITLE
getUsers returns awkward key `value` in JSON response

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#770]
Since recently, The API returns the users in a list identified by the key `value`.  See https://apiexplorersandbox.openbankproject.com/#3_0_0-getUsers

Previously, it was the key `users` which makes more sense to me. https://op-apiexplorer.openbankproject.com/#2_1_0-getUsers .  Could you please clarify why this change was made?

It makes the current API Manager throw a 500 at e.g. https://apimanagersandbox.openbankproject.com/users/ which needs to be fixed if `value` is to stay.

**Comment by sebtesobe** [comment]
API Manager has been made more robust to show an error message instead of a 500.

**Comment by constantine2nd** [comment]
@sebtesobe getUsers v3.0.0 is experimental used for testing Future. I will revert to v2.1.0 i.e. to previous state.

**Comment by sebtesobe** [comment]
Looks like the issue has been fixed, closing.
