### ISSUE TITLE
display_internal_errors not cover all the use cases

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-API#773]
OBPRestHelper just fixed  the errors in API level.

If it have some error in GateWay Login/ DirectLogin/ Auth Login, the errors are still swallowed....
eg:
code/api/OBPRestHelper.scala:199  code/api/OBPRestHelper.scala:199

It is better, when you package the Error in a box. Please log.error it first... 
It is good for coding ...

**Comment by simonredfern** [comment]
i.e. we also want to display errors from RESTHelper to the browser if display_internal_errors=true

**Comment by simonredfern** [comment]
Probably only need in the new auth header approach

**Comment by constantine2nd** [comment]
@hongwei1 Ready for testing.
