### ISSUE TITLE
Lost password form broken

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#785]
https://apisandbox.openbankproject.com/user_mgt/lost_password shows no form inputs, same on all other sandboxes i have looked at so far.

The served HTML shows `lostPasswordXhtml` from `src/main/scala/code/model/dataAccess/AuthUser.scala` verbatim, the `<user>` tags are not replaced by form inputs.

On first sight, it looks like a similar thing happened with sign up a few weeks ago, check commit 4e3d335732ab0a81f42c80b28366abf01ea30141 fixing a similar thing . Maybe it is a Lift upgrade issue?

**Comment by constantine2nd** [comment]
@sebtesobe Ready for testing.

**Comment by sebtesobe** [comment]
@constantine2nd The input field is back and reset password mails are sent. Thanks!
