### ISSUE TITLE
Add “available-funds” endpoint 

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#795]
Add an “available-funds” endpoint that returns yes or no to the query provided

GET only
/banks/BANK_ID/accounts/ACCOUNT_ID/view/VIEW_ID/available-funds/currency/CURRENCY/amount/AMOUNT

or 

/banks/BANK_ID/accounts/ACCOUNT_ID/view/VIEW_ID/available-funds?currency=CURRENCY&amount=AMOUNT

should return 
{answer: "yes" or "no",
date: Date,
available-funds-request-id: id}

Add can_read_available_funds to View permissions

**Comment by constantine2nd** [comment]
@simonredfern Ready for testing.

**Comment by constantine2nd** [comment]
Ready for testing.
