### ISSUE TITLE
Consider how we deal with account label for Kafka and Mapped going forward

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#81]
Some banks don't / won't have an "account label" returned with the account.

The account.label is how the account holder refers to their account e.g. "my savings account" "our new fishing boat account" etc.

It is updateable via 1.2.1 updateAccountLabel. However this call writes to the Mapped Account object / table - and with the Kafka connector this table is not populated so we will need to write this somewhere else.

We could create a new Mapped object  / Table AccountLabel that just stores account_id and label (and the insert / update date etc)

Then in all Mapped places where the label is referenced it should come from AccountLabel.

(Then a Kafka type connector can decide if this is get/set from/at the Bank or in OBP.)

Let's check the impact of this - What we would need to change? - including tests.

**Comment by marko-md** [comment]
The label field is used in next files:
- JSONFactory1.2.scala
  - at method createAccountJSON
- JSONFactory1.2.1.scala
  - at method createAccountJSON
- JSONFactory2.0.0.scala
  - at method createBasicAccountJSON
  - at method createCoreAccountJSON
- BankingData.scala
  - at method overviewJson
- View.scala
  - at method moderate
- SandboxDataLoadingTest.scala
  - at method verifyAccountCreated

According to a code Kafka populates the label field with a value of the number : 
```scala
  case class KafkaBankAccount(r: KafkaInboundAccount) extends BankAccount {
...
   def label : String              = r.number // Temp (label should be writable so customer can change)
...
}
```
