### ISSUE TITLE
Create function for crreateMappedAccountHolder (single point of access for each persistance operation)

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#84]
We have several instances of MappedAccountHolder.create in the code.

e.g.

          val holder = MappedAccountHolder.create
            .user(o)
            .accountBankPermalink(account.bank)
            .accountPermalink(account.id).saveMe
          logger.info(s"------------> created mappedUserHolder ${holder}")

 We should have single point of access to such a database / persisence function so we can consistently log / modify etc.

We should create a function crreateMappedAccountHolder which accepts three parameters (plus maybe the caller) and use that instead of raw calls to the Mapper ORM

**Comment by marko-md** [comment]
There is a forth optional parameter in the function call. In case it is defined a log will be made. Otherwise the log step will be skipped.
