### ISSUE TITLE
Recover Password not working 

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/OBP-API#85]
When trying to recover my password from an existing account using my email address, app says email doesn't exist

**Comment by simonredfern** [comment]
Please can you specify the host?

**Comment by joaomilho** [comment]
Still broken 

https://psd2-api.openbankproject.com/user_mgt/lost_password

<img width="1211" alt="screen shot 2017-10-30 at 0 19 22" src="https://user-images.githubusercontent.com/308196/32149651-0f0dbec6-bd08-11e7-9e0d-6ba9a224786a.png">

**Comment by constantine2nd** [comment]
@ichaib according to @simonredfern 
1. We have to use the username because email address is not unique.
2. Or if an email address is used, it should send multiple emails for each username it finds with that email address.
The second case is not implemented.

**Comment by joaomilho** [comment]
I still don't follow. This page simply doesn't have any field.

**Comment by sebtesobe** [comment]
@joaomilho Your issue is probably better covered by #785 .
