### ISSUE TITLE
Revising Dates and Date Times in OBP

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#850]
Dates and Date Times in OBP.

Currently all dates / date times in OBP are displayed as UTC date + time e.g. 2013-01-22T12:00:00Z 

However with some fields, e.g. date of birth, it doesn't really make sense to show a time component. - And by adding an artificial time component (e.g. 12:00) we can get unexpected results when the consumer displays the date with a large time zone difference. 

At the same time, we want to provide a consistent developer experience when it comes to parsing dates and date-times.

Thus:

Proposed changes.

There are two types of Dates in OBP.

**1) Dates which have no time components. (Date Only)**

e.g. Birthdays and contract dates.

The OBP adapter recieves a date (say 2017-11-29) from the core banking system.
The OBP adapter converts this to UTC and invents the time portion to be mid day on the day concerned e.g.
2013-01-22T12:00:00Z 

OBP-API recieves and uses this as a UTC Date internally.

In the JSON presentation layer, certain fields which we know to be Date Only are formatted in a fixed format of YYYY-MM-DD

The App can format the Date as it wishes.  

**2) Dates which have time components. (Date Time)**

e.g. Time stamps, API call logs (metrics), Creation dates and Expiry dates.

The adapter recieves a date-time (say 2017-11-29 13:45:15) from the core banking system.
The OBP adapter converts this to UTC e.g.
2013-01-22T13:45:15Z 

OBP-API recieves and uses this as a UTC Date internally.

OBP-API displays this unchanged.

The App can format the Date Time as it wishes.

**Comment by constantine2nd** [comment]
**1) Dates which have no time components. (Date Only)**
IMO we should not convert **Date Only => UTC** i.e.
_**Date Only** is NOT EQUAL for all cases to  **Date Only => UTC => Date Only**_

**Comment by constantine2nd** [comment]
Resolved.
