### ISSUE TITLE
Add roles and guards for addSocialMediaHandle getSocialMediaHandles 

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#86]
addSocialMediaHandle should be guarded by the Entitlement CanAddSocialMediaHandle
getSocialMediaHandles should be guarded by the Entitlement CanGetSocialMediaHandles

**Comment by marko-md** [comment]
End point /customers/CUSTOMER_NUMBER/social_media_handles does not have BANK_ID in url. We need it in order to check entitlements. 
@simonredfern Question is how to get the BANK_ID by CUSTOMER_NUMBER?

**Comment by simonredfern** [comment]
Please add bank_I'd to the URL
