### ISSUE TITLE
Add endpoint for entitlement_requests

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#869]
So a User can request an entitlement to a role

This will be called from API Explorer and API Manager

1) POST (uses currently logged in user)
/entitlement_requests

{  "bank_id":"String",  "role_name":"String"}

This will write into entitlement_request table.

2) GET
/users/USER_ID/entitlement_requests

3) GET
/entitlement_requests

Note: We can copy and modify: https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#v2_0_0-addEntitlement

**Comment by constantine2nd** [comment]
Implemented.
