### ISSUE TITLE
Ensure metrics durations are correct

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#885]

**Comment by constantine2nd** [comment]
Log in case of New Style Endpoint:

- APIUtil [INFO] Endpoint (GET) /users/current implemented in API version 3_0_0 took 14 Milliseconds

Log in case of Old Style Endpoint:

- TimeHelpers [INFO] Service request (GET) /obp/v2.1.0/users/current returned 200, took 19 Milliseconds

**Comment by constantine2nd** [comment]
The metrics are correct.
