### ISSUE TITLE
Strange Response for URL parameter

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-API#888]
<img width="1343" alt="strangeerror" src="https://user-images.githubusercontent.com/23308710/34978732-87cfddec-fa9f-11e7-8105-33c189a79224.png">

**Comment by constantine2nd** [comment]
Resolved by commit [Introuduced a new url parameter ?format=ISO20022 - fixed issue](https://github.com/OpenBankProject/OBP-API/commit/3dc4f0c25d16bbc25244327d59765b25314017ea)
