### ISSUE TITLE
create endpoint to list accounts owned even without owner view

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#934]
The endpoint should lists accounts for the current user where the current user is a holder but doesn't have the owner view.

See this for the table to use:
def getAccountHolders(bankId: BankId, accountId: AccountId): Set[User] = {

We'll need a new function def getAccountsHeld

URL 
/banks/BANK_ID/accounts-held

With this information, if a user does not yet have an owner view, they should be able to create one using other endpoints and the bank_id, account_id from this endpoint.

The json returned should include bank_id, account_id, label, number, routing address and routing scheme.

**Comment by hongwei1** [comment]
071b51697a1fbb43f6015a5e78660264d7c8e7b3
