### ISSUE TITLE
Metrics enhancements

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#944]
Default sort_by should be: date, DESC

Add sort info (sort_by, direction) to resource doc

Add correlationId to JSON response

Date in JSON should include milliseconds (check change on API Manager)

(Add duration to JSON response if possible)

Refactor val toConsumerId -> val consumerId etc.

**Comment by constantine2nd** [comment]
Currently done: 
- [x] Default sort_by should be: date, DESC

- [x] Add sort info (sort_by, direction) to resource doc

- [ ] Add correlationId to JSON response

- [ ] Date in JSON should include milliseconds (check change on API Manager)

- [ ] (Add duration to JSON response if possible)

- [x]  Refactor val toConsumerId -> val consumerId etc.

**Comment by constantine2nd** [comment]
@simonredfern Please check does filtering by these fields has to be fixed:

7 consumer_id  (if null ignore)

8 user_id (if null ignore)

9 anon (if null ignore) only support two value : true (return where user_id is null.) or false (return where user_id is not null.)

10 url (if null ignore), note: can not contain '&'.

11 app_name (if null ignore)

12 implemented_by_partial_function (if null ignore),

13 implemented_in_version (if null ignore)

14 verb (if null ignore)

According to the code only **9 anon** is implemented.
